import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import {
  LuSparkles,
  LuChevronDown,
  LuPlay,
  LuPause,
  LuUndo2,
  LuRedo2,
  LuMousePointer2,
  LuCrop,
  LuLayers,
  LuLock,
  LuLockOpen,
  LuType,
  LuTrash2,
  LuEye,
  LuEyeOff,
  LuLayoutGrid,
  LuShapes,
  LuImage,
  LuClapperboard,
  LuAudioLines,
  LuCircleDot,
  LuUpload,
  LuSquare,
  LuCircle,
  LuTriangle,
  LuMinus,
  LuMoveRight,
  LuStar,
  LuScan,
  LuMaximize,
  LuAperture,
  LuArrowUp,
  LuExpand,
  LuFlipVertical,
  LuRotateCw,
  LuActivity,
  LuVibrate,
  LuRefreshCcw,
  LuHeartPulse,
  LuZap,
  LuMoveHorizontal,
  LuPanelLeft,
  LuChevronsRight,
  LuLoader,
  LuHeart,
  LuCamera,
  LuBell,
  LuBookmark,
  LuCheck,
  LuCloud,
  LuFlag,
  LuGift,
  LuGlobe,
  LuHouse,
  LuMail,
  LuMapPin,
  LuMessageCircle,
  LuMusic,
  LuSettings,
  LuShield,
  LuSun,
  LuUser,
  LuVideo,
  LuWifi,
  LuLibrary,
} from "react-icons/lu";

type IconType = React.ComponentType<{ size?: number; color?: string; strokeWidth?: number }>;

const MAP: Record<string, IconType> = {
  spark: LuSparkles,
  chevron: LuChevronDown,
  play: LuPlay,
  pause: LuPause,
  undo: LuUndo2,
  redo: LuRedo2,
  cursor: LuMousePointer2,
  crop: LuCrop,
  layers: LuLayers,
  lock: LuLock,
  unlock: LuLockOpen,
  text: LuType,
  trash: LuTrash2,
  eye: LuEye,
  "eye-off": LuEyeOff,
  assets: LuLayoutGrid,
  icons: LuShapes,
  images: LuImage,
  videos: LuClapperboard,
  audio: LuAudioLines,
  background: LuCircleDot,
  uploads: LuUpload,
  charts: LuActivity,
  templates: LuLibrary,
  rect: LuSquare,
  circle: LuCircle,
  triangle: LuTriangle,
  line: LuMinus,
  arrow: LuMoveRight,
  star: LuStar,
  fit: LuScan,
  fullscreen: LuMaximize,
  fade: LuAperture,
  slide: LuArrowUp,
  pop: LuExpand,
  zoom: LuExpand,
  flip: LuFlipVertical,
  rotate: LuRotateCw,
  bounce: LuActivity,
  shake: LuVibrate,
  swing: LuRefreshCcw,
  pulse: LuHeartPulse,
  wobble: LuAudioLines,
  flash: LuZap,
  pan: LuMoveHorizontal,
  wipe: LuPanelLeft,
  push: LuChevronsRight,
  spin: LuLoader,
};

export function Icon({ name, size = 16 }: { name: string; size?: number }) {
  const Cmp = MAP[name] || LuCircle;
  return <Cmp size={size} />;
}

export const PRESET_ICON: Record<string, string> = {
  fadeIn: "fade",
  fadeOut: "fade",
  fade: "fade",
  slideUp: "slide",
  slideIn: "slide",
  slideOut: "slide",
  slide: "slide",
  popIn: "pop",
  popOut: "pop",
  zoomIn: "zoom",
  zoomOut: "zoom",
  zoom: "zoom",
  flipIn: "flip",
  rotateIn: "rotate",
  bounce: "bounce",
  shake: "shake",
  swing: "swing",
  pulse: "pulse",
  loopPulse: "pulse",
  wobble: "wobble",
  flash: "flash",
  pan: "pan",
  wipe: "wipe",
  push: "push",
  loopSpin: "spin",
};

export const LIBRARY_ICONS: { id: string; label: string; Icon: IconType }[] = [
  { id: "star", label: "Star", Icon: LuStar },
  { id: "heart", label: "Heart", Icon: LuHeart },
  { id: "zap", label: "Zap", Icon: LuZap },
  { id: "camera", label: "Camera", Icon: LuCamera },
  { id: "bell", label: "Bell", Icon: LuBell },
  { id: "bookmark", label: "Bookmark", Icon: LuBookmark },
  { id: "check", label: "Check", Icon: LuCheck },
  { id: "cloud", label: "Cloud", Icon: LuCloud },
  { id: "flag", label: "Flag", Icon: LuFlag },
  { id: "gift", label: "Gift", Icon: LuGift },
  { id: "globe", label: "Globe", Icon: LuGlobe },
  { id: "home", label: "Home", Icon: LuHouse },
  { id: "mail", label: "Mail", Icon: LuMail },
  { id: "pin", label: "Pin", Icon: LuMapPin },
  { id: "chat", label: "Chat", Icon: LuMessageCircle },
  { id: "music", label: "Music", Icon: LuMusic },
  { id: "settings", label: "Settings", Icon: LuSettings },
  { id: "shield", label: "Shield", Icon: LuShield },
  { id: "sun", label: "Sun", Icon: LuSun },
  { id: "user", label: "User", Icon: LuUser },
  { id: "video", label: "Video", Icon: LuVideo },
  { id: "wifi", label: "Wifi", Icon: LuWifi },
  { id: "image", label: "Image", Icon: LuImage },
  { id: "type", label: "Text", Icon: LuType },
];

export function iconDataUrl(Cmp: IconType, color = "#1a1433", size = 96) {
  const markup = renderToStaticMarkup(<Cmp size={size} color={color} strokeWidth={1.75} />);
  return `data:image/svg+xml;utf8,${encodeURIComponent(markup)}`;
}
