import type { AssetCategory, AssetDefinition, AssetField } from "./types";

const timingFields: AssetField[] = [
  { key: "startDelay", label: "Start delay (sec)", type: "number", hint: "Wait before the first animation", step: 0.01, min: 0 },
  { key: "stepDelay", label: "Step delay (sec)", type: "number", hint: "Pause between each event, node, chip, or bar", step: 0.01, min: 0 },
  { key: "connectDelay", label: "Connector delay (sec)", type: "number", hint: "Wait before drawing the line or link to the next item", step: 0.01, min: 0 },
  { key: "lineDuration", label: "Line draw time (sec)", type: "number", hint: "How long connectors, rails, spokes, and wipes take to draw", step: 0.01, min: 0.05 },
  { key: "revealDuration", label: "Reveal time (sec)", type: "number", hint: "How long each node, card, chip, or label takes to pop in", step: 0.01, min: 0.08 },
  { key: "itemDelays", label: "Per-item extra delays", type: "text", hint: "Optional extra pause before each item, comma-separated seconds", placeholder: "0, 0.4, 0.1" },
  { key: "sound", label: "Sound", type: "select", options: [{ label: "On (CC0)", value: "on" }, { label: "Off", value: "off" }] },
];

const timingDefaults = {
  startDelay: 0,
  stepDelay: 0.12,
  connectDelay: 0.08,
  lineDuration: 0.55,
  revealDuration: 0.32,
  itemDelays: "",
  sound: "on",
};

const base = {
  fps: 30,
  width: 1280,
  height: 720,
  durationInFrames: 150,
};

function make(
  partial: {
    id: string;
    name: string;
    description: string;
    category: AssetCategory;
    accent: string;
    template: string;
    durationInFrames?: number;
    fields: AssetField[];
    defaults: Record<string, string | number>;
  },
): AssetDefinition {
  return {
    ...base,
    durationInFrames: partial.durationInFrames ?? 150,
    id: partial.id,
    name: partial.name,
    description: partial.description,
    category: partial.category,
    accent: partial.accent,
    template: partial.template,
    fields: [...partial.fields, ...timingFields],
    defaults: { ...partial.defaults, ...timingDefaults },
  };
}

const colorFields = (accentDefault: string, bgDefault: string): AssetField[] => [
  { key: "accent", label: "Accent", type: "color" },
  { key: "bg", label: "Background", type: "color" },
];

/** Crime scene + documentary text templates (listed first in Assets). */
export const CRIME_DOC_ASSETS: AssetDefinition[] = [
  // —— Crime scene (22) ——
  make({
    id: "crime-board",
    name: "Crime board",
    description: "Cork board with four pinned notes; red strings draw pin-to-pin correctly.",
    category: "crime",
    accent: "#e63946",
    template: "crime-board",
    durationInFrames: 170,
    fields: [
      { key: "title", label: "Board title", type: "text" },
      { key: "label1", label: "Note 1", type: "text" },
      { key: "label2", label: "Note 2", type: "text" },
      { key: "label3", label: "Note 3", type: "text" },
      { key: "label4", label: "Note 4", type: "text" },
      ...colorFields("#e63946", "#1a1410"),
    ],
    defaults: {
      title: "Crime scene board",
      label1: "Suspect",
      label2: "Witness",
      label3: "Location",
      label4: "Evidence",
      accent: "#e63946",
      bg: "#1a1410",
    },
  }),
  make({
    id: "crime-string-web",
    name: "String web",
    description: "Multi-node conspiracy web — pins appear, then strings connect the network.",
    category: "crime",
    accent: "#e63946",
    template: "crime-string-web",
    durationInFrames: 160,
    fields: [
      { key: "title", label: "Title", type: "text" },
      ...colorFields("#e63946", "#1a1410"),
    ],
    defaults: { title: "The network", accent: "#e63946", bg: "#1a1410" },
  }),
  make({
    id: "crime-case-stamp",
    name: "Case stamp",
    description: "Case title, then CLASSIFIED / EXHIBIT stamp slam.",
    category: "crime",
    accent: "#e63946",
    template: "crime-case-stamp",
    fields: [
      { key: "stamp", label: "Stamp text", type: "text" },
      { key: "title", label: "Case title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      ...colorFields("#e63946", "#0a0c10"),
    ],
    defaults: {
      stamp: "CLASSIFIED",
      title: "Case file 47",
      subtitle: "Restricted — internal review only",
      accent: "#e63946",
      bg: "#0a0c10",
    },
  }),
  make({
    id: "crime-polaroid-cascade",
    name: "Polaroid cascade",
    description: "Three evidence polaroids drop onto the board one by one.",
    category: "crime",
    accent: "#e63946",
    template: "crime-polaroid-cascade",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "label1", label: "Photo 1", type: "text" },
      { key: "label2", label: "Photo 2", type: "text" },
      { key: "label3", label: "Photo 3", type: "text" },
      ...colorFields("#e63946", "#121018"),
    ],
    defaults: {
      title: "Evidence photos",
      label1: "Photo A",
      label2: "Photo B",
      label3: "Photo C",
      accent: "#e63946",
      bg: "#121018",
    },
  }),
  make({
    id: "crime-mugshot",
    name: "Mugshot reveal",
    description: "Booking photo plate, ID bar, then name and case number.",
    category: "crime",
    accent: "#e63946",
    template: "crime-mugshot",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "id", label: "Case ID", type: "text" },
      ...colorFields("#e63946", "#0a0c10"),
    ],
    defaults: { name: "UNKNOWN SUBJECT", id: "CASE-047", accent: "#e63946", bg: "#0a0c10" },
  }),
  make({
    id: "crime-evidence-tag",
    name: "Evidence tag",
    description: "Police evidence bag tag slam with case number.",
    category: "crime",
    accent: "#e63946",
    template: "crime-evidence-tag",
    fields: [
      { key: "tag", label: "Tag header", type: "text" },
      { key: "item", label: "Item description", type: "text" },
      { key: "caseId", label: "Case ID", type: "text" },
      ...colorFields("#e63946", "#0c0e12"),
    ],
    defaults: {
      tag: "EVIDENCE",
      item: "Cell phone — recovered 02:14",
      caseId: "#CF-221",
      accent: "#e63946",
      bg: "#0c0e12",
    },
  }),
  make({
    id: "crime-fingerprint",
    name: "Fingerprint scan",
    description: "Scan line sweeps a print circle; match percentage locks in.",
    category: "crime",
    accent: "#3ecf8e",
    template: "crime-fingerprint",
    fields: [
      { key: "label", label: "Label", type: "text" },
      { key: "percent", label: "Match %", type: "text" },
      ...colorFields("#3ecf8e", "#07090e"),
    ],
    defaults: { label: "PRINT MATCH", percent: "97%", accent: "#3ecf8e", bg: "#07090e" },
  }),
  make({
    id: "crime-timeline",
    name: "Crime timeline",
    description: "Vertical rail with timed incident beats — classic true-crime chronology.",
    category: "crime",
    accent: "#e63946",
    template: "crime-timeline",
    durationInFrames: 170,
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "events", label: "Events (one per line)", type: "textarea" },
      ...colorFields("#e63946", "#0a0c10"),
    ],
    defaults: {
      title: "Night of the incident",
      events: "22:10 Call received\n22:47 First on scene\n23:05 Evidence logged\n23:40 Suspect ID",
      accent: "#e63946",
      bg: "#0a0c10",
    },
  }),
  make({
    id: "crime-location-pin",
    name: "Crime location pin",
    description: "Radar rings pulse, then a pin drops onto the crime scene name.",
    category: "crime",
    accent: "#e63946",
    template: "crime-location-pin",
    fields: [
      { key: "place", label: "Place", type: "text" },
      { key: "city", label: "City / area", type: "text" },
      ...colorFields("#e63946", "#0a0c12"),
    ],
    defaults: { place: "Warehouse 9", city: "East docks", accent: "#e63946", bg: "#0a0c12" },
  }),
  make({
    id: "crime-clipping",
    name: "Newspaper clipping",
    description: "News clipping slaps onto screen with paper rotation settle.",
    category: "crime",
    accent: "#e63946",
    template: "crime-clipping",
    fields: [
      { key: "paper", label: "Paper name", type: "text" },
      { key: "headline", label: "Headline", type: "textarea" },
      ...colorFields("#e63946", "#101218"),
    ],
    defaults: {
      paper: "CITY CHRONICLE",
      headline: "Three missing after night raid",
      accent: "#e63946",
      bg: "#101218",
    },
  }),
  make({
    id: "crime-folder",
    name: "Case folder open",
    description: "Manila folder slides open to reveal the case name.",
    category: "crime",
    accent: "#e63946",
    template: "crime-folder",
    fields: [
      { key: "title", label: "Folder label", type: "text" },
      { key: "name", label: "Case name", type: "text" },
      ...colorFields("#e63946", "#0c0e12"),
    ],
    defaults: { title: "CASE FILE", name: "Operation Nightfall", accent: "#e63946", bg: "#0c0e12" },
  }),
  make({
    id: "crime-transcript",
    name: "Interrogation transcript",
    description: "Typewriter interrogation Q&A — documentary interview energy.",
    category: "crime",
    accent: "#e8c36a",
    template: "crime-transcript",
    durationInFrames: 170,
    fields: [
      { key: "label", label: "Label", type: "text" },
      { key: "line", label: "Transcript", type: "textarea" },
      ...colorFields("#e8c36a", "#07090e"),
    ],
    defaults: {
      label: "INTERROGATION",
      line: "Q: Where were you at midnight?\nA: I already told you — home.",
      accent: "#e8c36a",
      bg: "#07090e",
      lineDuration: 1.8,
    },
  }),
  make({
    id: "crime-cctv",
    name: "CCTV overlay",
    description: "Surveillance frame with REC blink, camera ID, and timestamp.",
    category: "crime",
    accent: "#3ecf8e",
    template: "crime-cctv",
    fields: [
      { key: "cam", label: "Camera label", type: "text" },
      { key: "stamp", label: "Timestamp", type: "text" },
      ...colorFields("#3ecf8e", "#050608"),
    ],
    defaults: {
      cam: "CAM 04 — ALLEY",
      stamp: "02:14:37  12/03",
      accent: "#3ecf8e",
      bg: "#050608",
    },
  }),
  make({
    id: "crime-chalk",
    name: "Chalk outline",
    description: "Chalk body outline draws on, then scene-marked label.",
    category: "crime",
    accent: "#f4efe6",
    template: "crime-chalk",
    fields: [
      { key: "label", label: "Label", type: "text" },
      ...colorFields("#f4efe6", "#1a1814"),
    ],
    defaults: { label: "SCENE MARKED", accent: "#f4efe6", bg: "#1a1814", lineDuration: 1.2 },
  }),
  make({
    id: "crime-photo-grid",
    name: "Evidence photo grid",
    description: "Six exhibit tiles pop into a forensics photo grid.",
    category: "crime",
    accent: "#e63946",
    template: "crime-photo-grid",
    durationInFrames: 160,
    fields: [
      { key: "title", label: "Title", type: "text" },
      ...colorFields("#e63946", "#0c0e12"),
    ],
    defaults: { title: "Evidence grid", accent: "#e63946", bg: "#0c0e12" },
  }),
  make({
    id: "crime-wanted",
    name: "Wanted poster",
    description: "Old-style WANTED poster slam with reward line.",
    category: "crime",
    accent: "#e63946",
    template: "crime-wanted",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "reward", label: "Reward line", type: "text" },
      ...colorFields("#e63946", "#141210"),
    ],
    defaults: { name: "JOHN DOE", reward: "REWARD $50,000", accent: "#e63946", bg: "#141210" },
  }),
  make({
    id: "crime-custody",
    name: "Chain of custody",
    description: "Custody transfer card — from officer to lab unit.",
    category: "crime",
    accent: "#e8c36a",
    template: "crime-custody",
    fields: [
      { key: "item", label: "Item", type: "text" },
      { key: "from", label: "From", type: "text" },
      { key: "to", label: "To", type: "text" },
      ...colorFields("#e8c36a", "#0a0c10"),
    ],
    defaults: {
      item: "Shell casing #3",
      from: "Officer Reyes",
      to: "Lab Unit B",
      accent: "#e8c36a",
      bg: "#0a0c10",
    },
  }),
  make({
    id: "crime-confession",
    name: "Confession quote",
    description: "Large confession pull-quote with attribution rule.",
    category: "crime",
    accent: "#e63946",
    template: "crime-confession",
    fields: [
      { key: "quote", label: "Quote", type: "textarea" },
      { key: "who", label: "Attribution", type: "text" },
      ...colorFields("#e63946", "#080a0e"),
    ],
    defaults: {
      quote: "I never meant for anyone to get hurt.",
      who: "— Suspect interview, tape 3",
      accent: "#e63946",
      bg: "#080a0e",
    },
  }),
  make({
    id: "crime-ballistic",
    name: "Ballistic note",
    description: "Shell casing graphic with caliber and lab match note.",
    category: "crime",
    accent: "#e63946",
    template: "crime-ballistic",
    fields: [
      { key: "caliber", label: "Caliber", type: "text" },
      { key: "note", label: "Lab note", type: "textarea" },
      ...colorFields("#e63946", "#0c0e12"),
    ],
    defaults: {
      caliber: "9mm",
      note: "Matched to weapon recovered in Unit 4",
      accent: "#e63946",
      bg: "#0c0e12",
    },
  }),
  make({
    id: "crime-night-zoom",
    name: "Surveillance zoom",
    description: "Night-vision style frame zooms in on a surveillance beat.",
    category: "crime",
    accent: "#3ecf8e",
    template: "crime-night-zoom",
    fields: [
      { key: "label", label: "Label", type: "text" },
      { key: "target", label: "Caption", type: "text" },
      ...colorFields("#3ecf8e", "#050608"),
    ],
    defaults: {
      label: "SURVEILLANCE ZOOM",
      target: "Subject enters frame",
      accent: "#3ecf8e",
      bg: "#050608",
    },
  }),
  make({
    id: "crime-redacted",
    name: "Redacted excerpt",
    description: "Declassified line with black redaction bar wipe.",
    category: "crime",
    accent: "#e63946",
    template: "crime-redacted",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "body", label: "Body text", type: "textarea" },
      ...colorFields("#e63946", "#0a0c10"),
    ],
    defaults: {
      title: "Declassified excerpt",
      body: "The transfer was authorized by ████ on 12 March.",
      accent: "#e63946",
      bg: "#0a0c10",
    },
  }),
  make({
    id: "crime-blood-trail",
    name: "Trail markers",
    description: "Drops appear along a path — trail documented beat.",
    category: "crime",
    accent: "#e63946",
    template: "crime-blood-trail",
    fields: [
      { key: "label", label: "Label", type: "text" },
      ...colorFields("#e63946", "#120e0e"),
    ],
    defaults: { label: "TRAIL DOCUMENTED", accent: "#e63946", bg: "#120e0e" },
  }),

  // —— Documentary text (21) ——
  make({
    id: "doctext-giant",
    name: "Giant word slam",
    description: "Huge documentary title word slam with accent rule + subtitle.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-giant",
    fields: [
      { key: "word", label: "Giant word", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      word: "EVIDENCE",
      subtitle: "What the official story left out",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-typewriter",
    name: "Archive typewriter",
    description: "Typewriter caption with caret — widely used archive note style.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-typewriter",
    fields: [
      { key: "label", label: "Label", type: "text" },
      { key: "line", label: "Line", type: "textarea" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      label: "ARCHIVE NOTE",
      line: "They never explained where the money went.",
      accent: "#e8c36a",
      bg: "#07080c",
      lineDuration: 1.6,
    },
  }),
  make({
    id: "doctext-stack",
    name: "Kinetic word stack",
    description: "Words slam stacked; last word hits in accent — kinetic typography staple.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-stack",
    durationInFrames: 160,
    fields: [
      { key: "text", label: "Words", type: "textarea", hint: "Space-separated, up to 6" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      text: "FOLLOW THE MONEY TRACE THE LIES",
      accent: "#e8c36a",
      bg: "#07080c",
      stepDelay: 0.1,
    },
  }),
  make({
    id: "doctext-lower-third",
    name: "Interview lower third",
    description: "Classic documentary lower third — name + role with accent bar.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-lower-third",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "role", label: "Role", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      name: "Dr. Amira Shah",
      role: "Investigative journalist",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-location",
    name: "Location chyron",
    description: "Place + date identifier — standard documentary location card.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-location",
    fields: [
      { key: "place", label: "Place", type: "text" },
      { key: "date", label: "Date", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      place: "Karachi, Pakistan",
      date: "March 12, 2019",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-chapter",
    name: "Chapter card",
    description: "Chapter eyebrow + title + rule — feature documentary section opener.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-chapter",
    fields: [
      { key: "chapter", label: "Chapter label", type: "text" },
      { key: "title", label: "Title", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      chapter: "CHAPTER 03",
      title: "The Money Trail",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-year",
    name: "Year punch",
    description: "Giant year slam — turning-point beat used across history docs.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-year",
    fields: [
      { key: "year", label: "Year", type: "number" },
      { key: "label", label: "Label", type: "text" },
      ...colorFields("#e8c36a", "#05070b"),
    ],
    defaults: { year: 1991, label: "THE TURNING POINT", accent: "#e8c36a", bg: "#05070b" },
  }),
  make({
    id: "doctext-quote",
    name: "Pull quote",
    description: "Italic pull quote with accent rule and attribution.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-quote",
    fields: [
      { key: "quote", label: "Quote", type: "textarea" },
      { key: "who", label: "Attribution", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      quote: "Democracy dies in darkness.",
      who: "— Editorial board",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-collide",
    name: "Split collide titles",
    description: "Two opposing titles slam toward center — contrast beat.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-collide",
    fields: [
      { key: "left", label: "Left title", type: "text" },
      { key: "right", label: "Right title", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: { left: "THEY SAID", right: "WE FOUND", accent: "#e8c36a", bg: "#07080c" },
  }),
  make({
    id: "doctext-whisper-shout",
    name: "Whisper then shout",
    description: "Soft line, then giant accent word — viral kinetic pattern.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-whisper-shout",
    fields: [
      { key: "soft", label: "Soft line", type: "text" },
      { key: "loud", label: "Loud word", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: { soft: "they whispered", loud: "CORRUPTION", accent: "#e8c36a", bg: "#07080c" },
  }),
  make({
    id: "doctext-counter",
    name: "Stat counter",
    description: "Counting big number with unit — money / casualty graphic staple.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-counter",
    fields: [
      { key: "prefix", label: "Prefix", type: "text" },
      { key: "value", label: "Value", type: "number" },
      { key: "suffix", label: "Suffix", type: "text" },
      { key: "label", label: "Label", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      prefix: "$",
      value: 240,
      suffix: "M",
      label: "Missing from the books",
      accent: "#e8c36a",
      bg: "#07080c",
      lineDuration: 1.1,
    },
  }),
  make({
    id: "doctext-lines",
    name: "Kinetic line cascade",
    description: "Multi-line claims slide in — common YouTube essay / doc rhythm.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-lines",
    durationInFrames: 160,
    fields: [
      { key: "lines", label: "Lines (one per line)", type: "textarea" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      lines: "First they denied it\nThen they delayed it\nThen the files vanished",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-focus",
    name: "Focus word sentence",
    description: "Sentence builds word-by-word; focus word scales up in accent.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-focus",
    durationInFrames: 160,
    fields: [
      { key: "sentence", label: "Sentence", type: "text" },
      { key: "focus", label: "Focus word", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      sentence: "The deal nobody voted for",
      focus: "nobody",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-vertical",
    name: "Vertical word drop",
    description: "Words drop stacked vertically — poster / trailer style.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-vertical",
    fields: [
      { key: "text", label: "Words", type: "textarea" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: { text: "POWER MONEY SILENCE", accent: "#e8c36a", bg: "#07080c" },
  }),
  make({
    id: "doctext-film-title",
    name: "Film title burn-in",
    description: "Slow title fade burn-in with film credit line.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-film-title",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "year", label: "Credit line", type: "text" },
      ...colorFields("#e8c36a", "#050508"),
    ],
    defaults: {
      title: "SHADOW STATE",
      year: "A BestMotions Film",
      accent: "#e8c36a",
      bg: "#050508",
    },
  }),
  make({
    id: "doctext-name-stack",
    name: "Name / role / org stack",
    description: "Three-line identity stack for interview subjects.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-name-stack",
    fields: [
      { key: "name", label: "Name", type: "text" },
      { key: "role", label: "Role", type: "text" },
      { key: "org", label: "Organization", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      name: "Elena Vargas",
      role: "Whistleblower",
      org: "Ministry of Finance",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-caption",
    name: "Archive caption bar",
    description: "Bottom caption bar wipe — archive footage label.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-caption",
    fields: [
      { key: "caption", label: "Caption", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: { caption: "Archive footage — 2004", accent: "#e8c36a", bg: "#07080c" },
  }),
  make({
    id: "doctext-impact",
    name: "Impact claim",
    description: "Hard claim slam with supporting line — essay / expose style.",
    category: "documentary",
    accent: "#e63946",
    template: "doctext-impact",
    fields: [
      { key: "claim", label: "Claim", type: "text" },
      { key: "support", label: "Support line", type: "text" },
      ...colorFields("#e63946", "#07080c"),
    ],
    defaults: {
      claim: "NO ONE WAS CHARGED",
      support: "After a three-year investigation",
      accent: "#e63946",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-compare",
    name: "Dual compare text",
    description: "Two opposing claims with center divider — he-said / records-show.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-compare",
    fields: [
      { key: "left", label: "Left claim", type: "text" },
      { key: "right", label: "Right claim", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      left: "Official story",
      right: "What records show",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-karaoke",
    name: "Karaoke subtitle",
    description: "Words highlight in sequence — lyric / VO follow style.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-karaoke",
    durationInFrames: 160,
    fields: [
      { key: "line", label: "Line", type: "text" },
      ...colorFields("#e8c36a", "#07080c"),
    ],
    defaults: {
      line: "Follow every transfer. Find every name.",
      accent: "#e8c36a",
      bg: "#07080c",
    },
  }),
  make({
    id: "doctext-opener",
    name: "Doc opener hook",
    description: "Eyebrow + question hook + underline — cold-open staple.",
    category: "documentary",
    accent: "#e8c36a",
    template: "doctext-opener",
    fields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "hook", label: "Hook", type: "textarea" },
      ...colorFields("#e8c36a", "#07090e"),
    ],
    defaults: {
      eyebrow: "TRUE STORY",
      hook: "What was really happening?",
      accent: "#e8c36a",
      bg: "#07090e",
    },
  }),
];
