import type { AssetDefinition, AssetField } from "./types";

const base = {
  fps: 30,
  width: 1280,
  height: 720,
  category: "newspaper" as const,
  isNew: true,
};

const timingFields: AssetField[] = [
  { key: "startDelay", label: "Start delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "stepDelay", label: "Step delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "connectDelay", label: "Connector delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "lineDuration", label: "String draw time (sec)", type: "number", step: 0.01, min: 0.05 },
  { key: "revealDuration", label: "Reveal time (sec)", type: "number", step: 0.01, min: 0.08 },
  { key: "itemDelays", label: "Per-item extra delays", type: "text", placeholder: "0, 0.4" },
  { key: "sound", label: "Sound", type: "select", options: [{ label: "On (CC0)", value: "on" }, { label: "Off", value: "off" }] },
];

const timingDefaults = {
  startDelay: 0,
  stepDelay: 0.14,
  connectDelay: 0.12,
  lineDuration: 0.45,
  revealDuration: 0.38,
  itemDelays: "",
  sound: "on",
};

const boardFields: AssetField[] = [
  { key: "title", label: "Board title", type: "text" },
  { key: "caption", label: "Hero caption", type: "text" },
  { key: "label1", label: "Card 1 label", type: "text" },
  { key: "label2", label: "Card 2 label", type: "text" },
  { key: "label3", label: "Card 3 label", type: "text" },
  { key: "label4", label: "Card 4 label", type: "text" },
  { key: "imageHero", label: "Hero photo", type: "image" },
  { key: "image1", label: "Card 1 photo", type: "image" },
  { key: "image2", label: "Card 2 photo", type: "image" },
  { key: "image3", label: "Card 3 photo", type: "image" },
  { key: "image4", label: "Card 4 photo", type: "image" },
  { key: "stringColor", label: "String color", type: "color" },
  { key: "paperColor", label: "Paper tint", type: "color" },
  { key: "placeholderColor", label: "Empty slot color", type: "color" },
];

const boardDefaults: Record<string, string | number> = {
  title: "CASE BOARD",
  caption: "Lead subject",
  label1: "Footage No.1",
  label2: "Footage No.2",
  label3: "Footage No.3",
  label4: "Footage No.4",
  imageHero: "",
  image1: "",
  image2: "",
  image3: "",
  image4: "",
  stringColor: "#e63946",
  paperColor: "#f2ebe0",
  placeholderColor: "#1a2744",
  ...timingDefaults,
};

export const NEWS_MYSTERY_ASSETS: AssetDefinition[] = [
  {
    ...base,
    id: "news-mystery-board",
    name: "Mystery evidence board",
    description:
      "Photoreal board: dusty textured wall, newsprint cards with scalloped edges, real pushpins, and fiber red string that draws pin-to-pin.",
    accent: "#e63946",
    template: "news-mystery-board",
    durationInFrames: 210,
    fields: [...boardFields, ...timingFields],
    defaults: { ...boardDefaults },
  },
  {
    ...base,
    id: "news-mystery-tour",
    name: "Mystery board camera tour",
    description:
      "Cinematic camera tour across the textured evidence wall — close on each photo, then pull back to the full string web.",
    accent: "#ff4d5a",
    template: "news-mystery-tour",
    durationInFrames: 250,
    fields: [...boardFields, ...timingFields],
    defaults: {
      ...boardDefaults,
      title: "THE NETWORK",
      caption: "Primary subject",
      revealDuration: 0.5,
    },
  },
  {
    ...base,
    id: "news-mystery-clippings",
    name: "Mystery news clippings board",
    description:
      "Newspaper clippings on a dusty split board with real pushpins, newsprint texture, and fiber string connections.",
    accent: "#c1121f",
    template: "news-mystery-clippings",
    durationInFrames: 210,
    fields: [
      ...boardFields,
      { key: "headline", label: "Hero headline", type: "textarea" },
      { key: "masthead", label: "Masthead", type: "text" },
      ...timingFields,
    ],
    defaults: {
      ...boardDefaults,
      title: "CLIPPINGS",
      caption: "Lead clipping",
      masthead: "THE DAILY RECORD",
      headline: "The story they tried to bury",
      label1: "Witness",
      label2: "Location",
      label3: "Timeline",
      label4: "Exhibit",
      placeholderColor: "#2a241c",
    },
  },
  {
    ...base,
    id: "news-mystery-page-dive",
    name: "Front page camera dive",
    description:
      "Textured newsprint front page pinned to a dusty desk — camera dives from masthead into the lead photo and headline.",
    accent: "#8b1e1e",
    template: "news-mystery-page-dive",
    durationInFrames: 180,
    fields: [
      { key: "masthead", label: "Masthead", type: "text" },
      { key: "headline", label: "Headline", type: "textarea" },
      { key: "highlight", label: "Kicker / highlight", type: "text" },
      { key: "body", label: "Deck", type: "textarea" },
      { key: "imageHero", label: "Lead photo", type: "image" },
      { key: "stringColor", label: "Accent", type: "color" },
      ...timingFields,
    ],
    defaults: {
      masthead: "THE MORNING TRIBUNE",
      headline: "Historic turnout reshapes the map overnight",
      highlight: "Historic turnout",
      body: "Crowds filled the avenues as tallies poured in from every district before dawn.",
      imageHero: "",
      stringColor: "#e63946",
      ...timingDefaults,
    },
  },
  {
    ...base,
    id: "news-mystery-clip-rail",
    name: "Clipping rail camera slide",
    description:
      "Four realistic newspaper clippings linked by fiber string — camera slides along the rail like a mystery board tour.",
    accent: "#d62828",
    template: "news-mystery-clip-rail",
    durationInFrames: 200,
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "masthead", label: "Masthead", type: "text" },
      { key: "label1", label: "Clip 1", type: "text" },
      { key: "label2", label: "Clip 2", type: "text" },
      { key: "label3", label: "Clip 3", type: "text" },
      { key: "label4", label: "Clip 4", type: "text" },
      { key: "image1", label: "Photo 1", type: "image" },
      { key: "image2", label: "Photo 2", type: "image" },
      { key: "image3", label: "Photo 3", type: "image" },
      { key: "image4", label: "Photo 4", type: "image" },
      { key: "stringColor", label: "String color", type: "color" },
      { key: "placeholderColor", label: "Empty slot", type: "color" },
      ...timingFields,
    ],
    defaults: {
      title: "THE TRAIL",
      masthead: "THE DAILY RECORD",
      label1: "Witness",
      label2: "Location",
      label3: "Timeline",
      label4: "Exhibit",
      image1: "",
      image2: "",
      image3: "",
      image4: "",
      stringColor: "#e63946",
      placeholderColor: "#1a2744",
      paperColor: "#f2ebe0",
      ...timingDefaults,
    },
  },
  {
    ...base,
    id: "news-mystery-stack-parallax",
    name: "Newspaper stack parallax",
    description:
      "Three textured newspaper plates stacked with real pushpins — camera rocks for a parallax 3D desk feel.",
    accent: "#f5d76e",
    template: "news-mystery-stack-parallax",
    durationInFrames: 190,
    fields: [
      { key: "masthead", label: "Masthead", type: "text" },
      { key: "headline", label: "Front headline", type: "textarea" },
      { key: "label1", label: "Back plate label", type: "text" },
      { key: "label2", label: "Mid plate label", type: "text" },
      { key: "stringColor", label: "Accent", type: "color" },
      ...timingFields,
    ],
    defaults: {
      masthead: "EVENING POST",
      headline: "Secrets buried in the archives finally surface",
      label1: "Earlier edition",
      label2: "Follow-up report",
      stringColor: "#e63946",
      ...timingDefaults,
    },
  },
];
