import type { AssetDefinition, AssetField } from "./types";

const base = {
  fps: 30,
  width: 1280,
  height: 720,
  durationInFrames: 140,
};

const timingFields: AssetField[] = [
  { key: "startDelay", label: "Start delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "stepDelay", label: "Step delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "connectDelay", label: "Connector delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "lineDuration", label: "Mark draw time (sec)", type: "number", step: 0.01, min: 0.05 },
  { key: "revealDuration", label: "Reveal time (sec)", type: "number", step: 0.01, min: 0.08 },
  { key: "itemDelays", label: "Per-item extra delays", type: "text", placeholder: "0, 0.4" },
  { key: "sound", label: "Sound", type: "select", options: [{ label: "On (CC0)", value: "on" }, { label: "Off", value: "off" }] },
];

const timingDefaults = {
  startDelay: 0,
  stepDelay: 0.12,
  connectDelay: 0.1,
  lineDuration: 0.55,
  revealDuration: 0.4,
  itemDelays: "",
  sound: "on",
};

const MARK_STYLE = [
  { label: "Highlighter", value: "highlight" },
  { label: "Underline", value: "underline" },
  { label: "Both", value: "both" },
];

const sharedFields: AssetField[] = [
  { key: "masthead", label: "Masthead", type: "text" },
  { key: "date", label: "Date line", type: "text" },
  { key: "headline", label: "Headline", type: "textarea" },
  { key: "highlight", label: "Phrase to mark", type: "text", hint: "Must appear inside the headline" },
  { key: "body", label: "Body copy", type: "textarea" },
  { key: "paperColor", label: "Newspaper color", type: "color" },
  { key: "ink", label: "Ink color", type: "color" },
  { key: "mastheadColor", label: "Masthead color", type: "color" },
  { key: "markerColor", label: "Highlighter color", type: "color" },
  { key: "underlineColor", label: "Underline color", type: "color" },
  {
    key: "markStyle",
    label: "Mark style",
    type: "select",
    options: MARK_STYLE,
    hint: "Highlighter wash, underline, or both",
  },
  { key: "tilt", label: "Settle tilt (degrees)", type: "number", step: 0.5 },
  { key: "flipAmount", label: "3D foreshorten", type: "number", hint: "0 = flat, higher = more edge-on feel", step: 0.01, min: 0, max: 0.4 },
  { key: "deskColor", label: "Desk / background", type: "color" },
];

const sharedDefaults: Record<string, string | number> = {
  masthead: "THE DAILY CHRONICLE",
  date: "Saturday, September 5, 2026",
  headline: "A defining moment for the nation",
  highlight: "defining moment",
  body: "In a landmark development, leaders gathered as history turned a new page. Analysts say the decision will reshape the decade ahead.",
  paperColor: "#f4ead8",
  ink: "#171310",
  mastheadColor: "#8b1e1e",
  markerColor: "#FAFF00",
  underlineColor: "#e63946",
  markStyle: "highlight",
  tilt: -4,
  flipAmount: 0.12,
  deskColor: "#0a0c12",
  ...timingDefaults,
};

function news3d(
  id: string,
  name: string,
  description: string,
  accent: string,
  extraFields: AssetField[] = [],
  extraDefaults: Record<string, string | number> = {},
): AssetDefinition {
  return {
    ...base,
    id,
    name,
    description,
    category: "newspaper",
    accent,
    template: id,
    isNew: true,
    fields: [...sharedFields, ...extraFields, ...timingFields],
    defaults: { ...sharedDefaults, ...extraDefaults },
  };
}

export const NEWS_3D_ASSETS: AssetDefinition[] = [
  news3d(
    "news-3d-flip",
    "3D page flip (clean)",
    "Clean rectangular newspaper flips from edge-on onto the desk — no tears. Customize paper color, then highlighter or underline.",
    "#f5d76e",
    [],
    { markStyle: "both", paperColor: "#f7efe0" },
  ),
  news3d(
    "news-3d-tilt-rotate",
    "3D tilt rotate",
    "Paper rocks in fake 3D (scale foreshortening + rotation). Change newspaper color, tilt, and mark style.",
    "#7ec8e3",
    [],
    { markStyle: "underline", underlineColor: "#1d6fd8", tilt: -6, flipAmount: 0.18 },
  ),
  news3d(
    "news-3d-spin-desk",
    "3D spin onto desk",
    "Clean sheet spins and lands on the desk, then paints the phrase. Full paper / ink / marker colors.",
    "#e07040",
    [],
    { paperColor: "#efe4cc", markStyle: "highlight", markerColor: "#ffe566" },
  ),
  news3d(
    "news-3d-card-float",
    "3D floating plate",
    "Floating clean newspaper card with a gentle perspective rock, then highlight or underline.",
    "#b090e0",
    [],
    { paperColor: "#f2e8f4", markStyle: "both", markerColor: "#e8b4ff" },
  ),
  news3d(
    "news-3d-open-fold",
    "3D center unfold",
    "Sheet opens from a thin center fold (no rip). Color the paper and choose highlighter / underline.",
    "#5cbf6a",
    [],
    { paperColor: "#eef6ea", markStyle: "highlight" },
  ),
  news3d(
    "news-3d-stack-rotate",
    "3D stack rotate",
    "Clean stack underneath; top sheet rotates into place in 3D. Tint the top and under sheets.",
    "#c9893d",
    [
      { key: "paperColorAlt", label: "Under sheet color", type: "color" },
      { key: "paperColorAlt2", label: "Bottom sheet color", type: "color" },
    ],
    {
      paperColor: "#f4ead8",
      paperColorAlt: "#ebe0cc",
      paperColorAlt2: "#e4d8c0",
      markStyle: "both",
    },
  ),
  news3d(
    "news-3d-underline-sweep",
    "Clean underline sweep",
    "No tears — sharp sheet on desk. Underline (or highlighter) sweeps the phrase. Recolor the paper freely.",
    "#e63946",
    [],
    { markStyle: "underline", underlineColor: "#e63946", paperColor: "#faf6ee" },
  ),
  news3d(
    "news-3d-marker-pass",
    "Clean marker pass",
    "Ken-Burns push on a clean sheet, then a highlighter pass. Paper, ink, and marker colors are all editable.",
    "#FAFF00",
    [],
    { markStyle: "highlight", markerColor: "#FAFF00", paperColor: "#f1e6d0" },
  ),
  news3d(
    "news-3d-hero-plate",
    "3D hero front plate",
    "Large clean front page settles from depth into place, then marks the headline phrase.",
    "#8b1e1e",
    [],
    { markStyle: "both", paperColor: "#f8f0e2", tilt: -2 },
  ),
  news3d(
    "news-3d-side-turn",
    "3D side page turn",
    "Page turns in from the side over a clean under-sheet — rotatable 3D feel, no tears.",
    "#4ec4ff",
    [{ key: "paperColorAlt", label: "Back page color", type: "color" }],
    {
      paperColor: "#f4ead8",
      paperColorAlt: "#e8dcc8",
      markStyle: "underline",
      underlineColor: "#0d6efd",
    },
  ),
  {
    ...base,
    id: "news-3d-real-flip",
    name: "Real 3D page flip",
    description:
      "Photoreal newsprint texture + wooden desk. Page flips from edge-on with soft contact shadow — not flat dummy paper.",
    category: "newspaper" as const,
    accent: "#c4a574",
    template: "news-3d-real-flip",
    isNew: true,
    fields: [...sharedFields, ...timingFields],
    defaults: { ...sharedDefaults, markStyle: "both", paperColor: "#f3e9d6", deskColor: "#1a1410" },
  },
  {
    ...base,
    id: "news-3d-real-spin",
    name: "Real 3D desk spin",
    description:
      "Textured newspaper spins onto a real desk plate with foreshortening and newsprint grain.",
    category: "newspaper" as const,
    accent: "#d4a574",
    template: "news-3d-real-spin",
    isNew: true,
    fields: [...sharedFields, ...timingFields],
    defaults: { ...sharedDefaults, markStyle: "highlight", paperColor: "#f0e4cc", deskColor: "#16110e" },
  },
  {
    ...base,
    id: "news-3d-real-stack",
    name: "Real 3D stack",
    description:
      "Layered textured sheets on wood; top page rotates into place in fake-3D with shadows.",
    category: "newspaper" as const,
    accent: "#b8956a",
    template: "news-3d-real-stack",
    isNew: true,
    fields: [
      ...sharedFields,
      { key: "paperColorAlt", label: "Under sheet color", type: "color" },
      { key: "paperColorAlt2", label: "Bottom sheet color", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...sharedDefaults,
      paperColor: "#f4ead8",
      paperColorAlt: "#ebe0cc",
      paperColorAlt2: "#e4d8c0",
      markStyle: "both",
      deskColor: "#18120e",
    },
  },
  {
    ...base,
    id: "news-3d-real-turn",
    name: "Real 3D page turn",
    description:
      "Photoreal side page turn over a textured under-sheet on wooden desk — production paper look.",
    category: "newspaper" as const,
    accent: "#c9a06a",
    template: "news-3d-real-turn",
    isNew: true,
    fields: [
      ...sharedFields,
      { key: "paperColorAlt", label: "Back page color", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...sharedDefaults,
      paperColor: "#f4ead8",
      paperColorAlt: "#e8dcc8",
      markStyle: "underline",
      underlineColor: "#8b1e1e",
      deskColor: "#15110d",
    },
  },
  {
    ...base,
    durationInFrames: 270,
    id: "news-3d-vox-tour",
    name: "Vox camera tour",
    description:
      "Vox-style multi-plane article tour: dark void, textured plates at fake Z-depth, camera flies between them with focus dimming + headline mark.",
    category: "newspaper" as const,
    accent: "#f5d76e",
    template: "news-3d-vox-tour",
    isNew: true,
    fields: [
      ...sharedFields,
      { key: "headline2", label: "Left plate headline", type: "textarea" },
      { key: "body2", label: "Left plate body", type: "textarea" },
      { key: "headline3", label: "Right plate headline", type: "textarea" },
      { key: "body3", label: "Right plate body", type: "textarea" },
      { key: "paperColorAlt", label: "Left paper color", type: "color" },
      { key: "paperColorAlt2", label: "Right paper color", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...sharedDefaults,
      headline: "A defining moment for the nation",
      highlight: "defining moment",
      body: "Leaders gathered as history turned a new page — analysts say the decade ahead will shift.",
      headline2: "Markets scramble as filings land overnight",
      body2: "Trading desks watched exchange notices as volumes spiked before the close.",
      headline3: "Regulators open a formal review",
      body3: "Officials said the inquiry will examine disclosures from the prior quarter.",
      paperColor: "#f4ead8",
      paperColorAlt: "#ebe0cc",
      paperColorAlt2: "#e4d8c0",
      deskColor: "#07080c",
      markStyle: "both",
      tilt: -3,
      revealDuration: 0.55,
      lineDuration: 0.65,
    },
  },
  {
    ...base,
    durationInFrames: 210,
    id: "news-3d-vox-rack",
    name: "Vox focus rack",
    description:
      "Start soft on a far plate, then rack the camera onto the hero article and paint the phrase — fake DOF via dim/veil.",
    category: "newspaper" as const,
    accent: "#7ec8e3",
    template: "news-3d-vox-rack",
    isNew: true,
    fields: [
      ...sharedFields,
      { key: "headline2", label: "Far plate headline", type: "textarea" },
      { key: "body2", label: "Far plate body", type: "textarea" },
      { key: "paperColorAlt", label: "Far paper color", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...sharedDefaults,
      headline2: "Earlier briefing notes",
      body2: "A quieter page from the archive sits behind the lead story.",
      paperColorAlt: "#e6dcc8",
      deskColor: "#06070b",
      markStyle: "highlight",
      revealDuration: 0.6,
    },
  },
  {
    ...base,
    durationInFrames: 220,
    id: "news-3d-vox-orbit",
    name: "Vox parallax orbit",
    description:
      "Hero article center-stage; satellite plates parallax while the camera orbits — closest Revideo match to AE 3D camera feel.",
    category: "newspaper" as const,
    accent: "#e07040",
    template: "news-3d-vox-orbit",
    isNew: true,
    fields: [
      ...sharedFields,
      { key: "headline2", label: "Right satellite label", type: "text" },
      { key: "headline3", label: "Left satellite label", type: "text" },
      { key: "paperColorAlt", label: "Right paper color", type: "color" },
      { key: "paperColorAlt2", label: "Left paper color", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...sharedDefaults,
      headline2: "MARKETS",
      headline3: "BRIEFING",
      paperColorAlt: "#e8dcc8",
      paperColorAlt2: "#ddd2bc",
      deskColor: "#07090e",
      markStyle: "both",
      tilt: -2,
    },
  },
  {
    ...base,
    durationInFrames: 300,
    id: "news-3d-vox-doc",
    name: "Vox 3D document tour",
    description:
      "Investigative dossier cinematic: camera flies overview → headline → evidence → quote with yellow stroke highlighter draws. All copy is editable.",
    category: "newspaper" as const,
    accent: "#e2b714",
    template: "news-3d-vox-doc",
    isNew: true,
    fields: [
      { key: "tag", label: "Dossier tag / kicker", type: "text" },
      { key: "headline", label: "Headline", type: "textarea" },
      { key: "meta", label: "Meta / byline", type: "text" },
      { key: "lead", label: "Lead paragraph", type: "textarea" },
      { key: "body", label: "Left body copy", type: "textarea" },
      { key: "evidence", label: "Evidence (right column)", type: "textarea" },
      { key: "keyFinding", label: "Key finding box", type: "textarea" },
      { key: "quote", label: "Quoted statement", type: "textarea" },
      { key: "paperColor", label: "Paper color", type: "color" },
      { key: "ink", label: "Ink color", type: "color" },
      { key: "mastheadColor", label: "Tag color", type: "color" },
      { key: "markerColor", label: "Highlighter color", type: "color" },
      { key: "deskColor", label: "Background", type: "color" },
      ...timingFields,
    ],
    defaults: {
      ...timingDefaults,
      tag: "Investigative Dossier · Special Report",
      headline: "Uncovering The Shell Company Network",
      meta: "Filed by Financial Audit Bureau · Case Ref: #2026-X94",
      lead: "Over sixteen months of wire transfers revealed a continuous redirection of capital through offshore intermediaries.",
      body: "Records obtained through leaked banking affidavits indicate that entities registered in Delaware and Cyprus shared identical corporate directors. These transactions bypassed standard screening mechanisms under the guise of intellectual property licensing fees.",
      evidence:
        "According to internal correspondence dated August 14, executives knowingly approved duplicate balance statements to reassure retail institutional underwriters.",
      keyFinding:
        "Cross-jurisdictional filings failed to disclose ultimate beneficial owners across all 3 subsidiary holding firms.",
      quote:
        '"Total unaccounted capital moved between fiscal quarters 2 and 4 exceeded forty-eight million dollars without physical inventory matching."',
      paperColor: "#f7f5ed",
      ink: "#1a1a1a",
      mastheadColor: "#9c2727",
      markerColor: "#ffd43f",
      deskColor: "#0f1117",
      startDelay: 0.15,
      revealDuration: 0.85,
      lineDuration: 0.75,
      sound: "on",
    },
  },
];
