import type { AssetDefinition, AssetField } from "./types";

const base = {
  fps: 30,
  width: 1280,
  height: 720,
  durationInFrames: 180,
};

const timingFields: AssetField[] = [
  { key: "startDelay", label: "Start delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "stepDelay", label: "Step delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "connectDelay", label: "Connector delay (sec)", type: "number", step: 0.01, min: 0 },
  { key: "lineDuration", label: "Motion time (sec)", type: "number", step: 0.01, min: 0.05 },
  { key: "revealDuration", label: "Reveal time (sec)", type: "number", step: 0.01, min: 0.08 },
  { key: "itemDelays", label: "Per-item extra delays", type: "text", placeholder: "0, 0.3" },
  { key: "sound", label: "Sound", type: "select", options: [{ label: "On (CC0)", value: "on" }, { label: "Off", value: "off" }] },
];

const timingDefaults = {
  startDelay: 0,
  stepDelay: 0.2,
  connectDelay: 0.1,
  lineDuration: 0.9,
  revealDuration: 0.35,
  itemDelays: "",
  sound: "on",
};

const PLACE_OPTIONS = [
  { label: "India", value: "india" },
  { label: "USA", value: "usa" },
  { label: "United Kingdom", value: "uk" },
  { label: "China", value: "china" },
  { label: "Russia", value: "russia" },
  { label: "Pakistan", value: "pakistan" },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Japan", value: "japan" },
  { label: "France", value: "france" },
  { label: "Germany", value: "germany" },
  { label: "Australia", value: "australia" },
  { label: "Brazil", value: "brazil" },
  { label: "South Africa", value: "south-africa" },
  { label: "UAE", value: "uae" },
  { label: "Israel", value: "israel" },
];

const STYLE_OPTIONS = [
  { label: "Satellite", value: "satellite" },
  { label: "Street", value: "street" },
  { label: "Topographic", value: "topo" },
  { label: "Dark gray", value: "dark" },
];

function real(
  id: string,
  name: string,
  description: string,
  accent: string,
  fields: AssetField[],
  defaults: Record<string, string | number>,
  durationInFrames = 180,
): AssetDefinition {
  return {
    ...base,
    durationInFrames,
    id,
    name,
    description,
    category: "maps",
    accent,
    template: id,
    fields: [...fields, ...timingFields],
    defaults: { ...timingDefaults, ...defaults },
  };
}

export const REAL_MAP_ASSETS: AssetDefinition[] = [
  real(
    "real-sat-zoom",
    "Satellite zoom into city",
    "Real Esri World Imagery — Ken Burns zoom into a capital, then a pin drops.",
    "#ff5a3a",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "City / country", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "spanLat", label: "View span (° lat)", type: "number", step: 0.01, min: 0.05, hint: "Smaller = closer zoom" },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "New Delhi",
      subtitle: "Satellite · capital metro",
      placeKey: "india",
      mapStyle: "satellite",
      spanLat: 0.55,
      accent: "#ff5a3a",
      bg: "#05080d",
      lineDuration: 1.2,
    },
  ),
  real(
    "real-street-pin",
    "Street map pin drop",
    "Real Esri street basemap of the capital with a location pin.",
    "#1d6fd8",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "City / country", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "London",
      subtitle: "Street map · capital",
      placeKey: "uk",
      mapStyle: "street",
      accent: "#1d6fd8",
      bg: "#0a0c10",
    },
  ),
  real(
    "real-sat-route",
    "Satellite route corridor",
    "Real satellite frame covering two cities with an animated route line.",
    "#ffbf00",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "fromPlace", label: "From", type: "select", options: PLACE_OPTIONS },
      { key: "toPlace", label: "To", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Route color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "India → UAE",
      subtitle: "Satellite corridor",
      fromPlace: "india",
      toPlace: "uae",
      mapStyle: "satellite",
      accent: "#ffbf00",
      bg: "#05080d",
      lineDuration: 1.2,
    },
  ),
  real(
    "real-zoom-levels",
    "Earth-style zoom levels",
    "Real satellite imagery steps: continent → region → city, then pin.",
    "#ff5a3a",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Focus place", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Tokyo",
      subtitle: "Continent → city",
      placeKey: "japan",
      mapStyle: "satellite",
      accent: "#ff5a3a",
      bg: "#05080d",
      stepDelay: 0.25,
      lineDuration: 0.85,
    },
  ),
  real(
    "real-topo-pan",
    "Topographic pan",
    "Real Esri topographic basemap with a slow lateral pan.",
    "#7ddea2",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Region", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Accent", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "France",
      subtitle: "Topographic basemap",
      placeKey: "france",
      mapStyle: "topo",
      accent: "#7ddea2",
      bg: "#0a100c",
      lineDuration: 1.4,
    },
  ),
  real(
    "real-dual-compare",
    "Street vs satellite split",
    "Side-by-side real street map and satellite imagery of the same capital.",
    "#5ce1ff",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Place", type: "select", options: PLACE_OPTIONS },
      { key: "accent", label: "Accent", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Washington, D.C.",
      subtitle: "Street  ·  Satellite",
      placeKey: "usa",
      accent: "#5ce1ff",
      bg: "#05080d",
    },
  ),
  real(
    "real-region-sweep",
    "Regional satellite sweep",
    "Wide real satellite view with a cinematic pan across the region.",
    "#ff9933",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Region", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Accent", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Australia",
      subtitle: "Regional satellite sweep",
      placeKey: "australia",
      mapStyle: "satellite",
      accent: "#ff9933",
      bg: "#05080d",
      lineDuration: 1.5,
    },
  ),
  real(
    "real-dark-pin",
    "Dark basemap pin",
    "Real dark-gray basemap with a glowing capital pin — news-desk style.",
    "#ffd060",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Place", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Berlin",
      subtitle: "Dark basemap",
      placeKey: "germany",
      mapStyle: "dark",
      accent: "#ffd060",
      bg: "#050608",
    },
  ),
  real(
    "real-sat-orbit",
    "Satellite orbit pass",
    "Real satellite plate with a gentle orbit-style rotation and settle.",
    "#7ddea2",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Place", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Accent", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Brasília",
      subtitle: "Satellite orbit pass",
      placeKey: "brazil",
      mapStyle: "satellite",
      accent: "#7ddea2",
      bg: "#05080d",
      lineDuration: 1.3,
    },
  ),
  real(
    "real-multi-hop",
    "Multi-city satellite hops",
    "Cuts between real satellite frames of three capitals, YouTuber travel style.",
    "#5ce1ff",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "fromPlace", label: "Stop 1", type: "select", options: PLACE_OPTIONS },
      { key: "viaPlace", label: "Stop 2", type: "select", options: PLACE_OPTIONS },
      { key: "toPlace", label: "Stop 3", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "USA → UK → India",
      subtitle: "Multi-city satellite hops",
      fromPlace: "usa",
      viaPlace: "uk",
      toPlace: "india",
      mapStyle: "satellite",
      accent: "#5ce1ff",
      bg: "#05080d",
      stepDelay: 0.2,
    },
    240,
  ),
  real(
    "real-street-push",
    "Street-level push-in",
    "Tight real street basemap with a strong Ken Burns push into the block.",
    "#e63946",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Place", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "accent", label: "Accent", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Paris",
      subtitle: "Street-level push-in",
      placeKey: "france",
      mapStyle: "street",
      accent: "#e63946",
      bg: "#0a0c10",
      lineDuration: 1.4,
    },
  ),
  real(
    "real-coastal-sat",
    "Coastal satellite focus",
    "Real satellite framing that keeps ocean and shoreline in view, then pins the city.",
    "#3a9fd4",
    [
      { key: "title", label: "Title", type: "text" },
      { key: "subtitle", label: "Subtitle", type: "text" },
      { key: "placeKey", label: "Coastal place", type: "select", options: PLACE_OPTIONS },
      { key: "mapStyle", label: "Basemap", type: "select", options: STYLE_OPTIONS },
      { key: "lonBias", label: "Ocean shift (° lon)", type: "number", step: 0.01 },
      { key: "latBias", label: "Ocean shift (° lat)", type: "number", step: 0.01 },
      { key: "accent", label: "Pin color", type: "color" },
      { key: "bg", label: "Background", type: "color" },
    ],
    {
      title: "Dubai / Abu Dhabi",
      subtitle: "Coastal satellite",
      placeKey: "uae",
      mapStyle: "satellite",
      lonBias: 0.12,
      latBias: 0.05,
      accent: "#3a9fd4",
      bg: "#041018",
      lineDuration: 1.2,
    },
  ),
];
